-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for the watchlist
create table watchlist (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  movie_id integer not null,
  title text not null,
  poster_path text,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(user_id, movie_id)
);

alter table watchlist enable row level security;

create policy "Users can view their own watchlist." on watchlist
  for select using (auth.uid() = user_id);

create policy "Users can add to their own watchlist." on watchlist
  for insert with check (auth.uid() = user_id);

create policy "Users can delete from their own watchlist." on watchlist
  for delete using (auth.uid() = user_id);

-- This trigger automatically creates a profile entry when a new user signs up via Supabase Auth.
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
